### ISSUE TITLE
Scoring doesn't work

### ISSUE THREAD

**Issue by hyunjae-lee** [opensource-projectteam16/Vamap#10]
**Describe the bug**
Scoring 을 하고 결과를 보면, 유저 데이터 범위 내에 아무런 데이터가 없어도 특정 값들이 나타납니다. 

**To Reproduce**
1. $python main.py Setup.txt 실행
2. MAP.html 결과 확인

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by sangminBangbada** [comment]
해당 Issue에 대한 문제 확인하였습니다.
최적화 단계에서 초기 엑셀파일 정렬과 Scoring 코드가 호환되지 않아 나타나는 문제였습니다.
현재 문제 해결 완료하여 다음 사진 같이 옳은 값이 출력됨을 보실 수 있습니다.
![image](https://user-images.githubusercontent.com/39620529/58641915-2218c780-8337-11e9-886a-e4c380a09ad4.png)
![image](https://user-images.githubusercontent.com/39620529/58642062-7754d900-8337-11e9-8b39-17a8454376af.png)
해당 내용은 Contribute브랜치에 Fixup issue #10 으로 Push 했습니다.
감사합니다
