### ISSUE TITLE
Need user-weight

### ISSUE THREAD

**Issue by sangminBangbada** [opensource-projectteam16/Vamap#11]
**Is your feature request related to a problem? Please describe.**
유저간의 연산에 적용할 User_Weight이 필요합니다

**Describe the solution you'd like**
Scoring으로 넘어오늘 다른 데이터 딕셔너리와 같은 형태로
User_data가 Pasing 되어야 합니다.

**Comment by alstjdwo1601** [comment]
Setup.txt 에서 사용자가 User_data 를 입력할 때 이에 대한 weight값을 입력하게끔 Setup.txt 에 가이드해주는 말을 추가하고, 실제로 이 weight값 또한 마지막에 parser.py 에서 main.py 에 결과값을 보낼때
같이 보내서 scoring.py에서 호출하면 같이 넘어가게끔 수정하겠습니다.
