### ISSUE TITLE
[OSS] requirements 수정 및 설치법에 반영

### ISSUE THREAD

**Issue by njw1204** [opensource-projectteam16/Vamap#13]
@ ```Pull request``` 보내기 전에 반드시 ```Issue```를 아래의 템플릿으로 작성하여 주세요. 

@ 해당 ```Issue``` 를 저희 팀에서 검토하고, 해결이 필요한 ```Issue```일 경우 ```Pull request``` 요청을 드릴게요.

@ ```Pull request``` 를 진행하실 때는, 본 프로젝트의 ```contribute``` 브랜치에 요청해주세요.

1. 이슈 제목
**requirements 수정 및 설치법에 반영**

2. 이슈 발생 환경
  2.1 이슈 환경
  **Python 3.6 / Windows 10**

3. 이슈 내용
3.1 자세한 내용
  README.md의 설치법에 나온대로 folium만 설치하게 되면 아래와 같은 오류가 발생합니다. requirements.txt로 설치하려고 해도, 현재 requirements.txt에는 필요 없는 패키지가 다수 포함되어 있어서 설치가 어렵습니다. 프로젝트를 분석해서 필요한 패키지만 requirements에 남기고 README.md의 설치법을 수정하고자 합니다.

 3.2 스크린샷 및 결과 로그
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by hyunjae-lee** [comment]
네, 저희도 requirements.txt는 초기에만 설정해놓고 maintenance 과정이 마무리 될 때쯤 수정하려 했습니다.
requirements.txt 및 Readme.md에 contribution을 해주신다면 감사하겠습니다.

**Comment by alstjdwo1601** [comment]
저희 requirements.txt 에 있던 패키지중에 필요없는 것들을 확인해서 제거했고 저희 프로그램을 맨 처음 클론하여 쓸 때 참고 할 수있는requirement guide를 추가하였습니다.
의견 감사드립니다.
