### ISSUE TITLE
[OSS] CSV 파일에 대한 Roadmanager.py 실행

### ISSUE THREAD

**Issue by sangminBangbada** [opensource-projectteam16/Vamap#14]
@ ```Pull request``` 보내기 전에 반드시 ```Issue```를 아래의 템플릿으로 작성하여 주세요. 

@ 해당 ```Issue``` 를 저희 팀에서 검토하고, 해결이 필요한 ```Issue```일 경우 ```Pull request``` 요청을 드릴게요.

@ ```Pull request``` 를 진행하실 때는, 본 프로젝트의 ```contribute``` 브랜치에 요청해주세요.

1. 이슈 제목
 CSV 파일에 대한 Roadmanager.py 실행

2. 이슈 발생 환경
  2.1 이슈 환경
Linux & Window
CSV File
  2.2 기타 환경 (특정 코드 지적 가능)

3. 이슈 내용
 3.1 자세한 내용
roadmanager.py가 CSV파일에 대해서 동작하지 않습니다

 3.2 스크린샷 및 결과 로그
![image](https://user-images.githubusercontent.com/39620529/59028038-8686da00-8895-11e9-8344-6000a2a8fec9.png)

**Comment by hyunjae-lee** [comment]
roadmanager.py는 xlsx파일만 허용하고 있습니다.
