### ISSUE TITLE
Logo copyright issue

### ISSUE THREAD

**Issue by ihooni** [opensource-projectteam16/Vamap#16]
I found a service called 'MapTiler' and its logo is same as 'Vamap'.
I think the copyright issue may occur because their logo(trademark) is registered in Switzerland and other countries.
You should change this problem.

Check this copyright notice from the service's [website](https://www.maptiler.com/terms-of-use/).
<img width="694" alt="스크린샷 2019-06-21 오후 5 20 20" src="https://user-images.githubusercontent.com/37792049/59908913-72bca580-9449-11e9-8375-9110a3b218d2.png">

**Comment by smallfish06** [comment]
Thank you for your respond:) We checked copyright issue and changed our logo
