### ISSUE TITLE
[OSS] 데이터 연산시간이 오래걸립니다.

### ISSUE THREAD

**Issue by jjiijj78** [opensource-projectteam16/Vamap#17]
@ ```Pull request``` 보내기 전에 반드시 ```Issue```를 아래의 템플릿으로 작성하여 주세요. 

@ 해당 ```Issue``` 를 저희 팀에서 검토하고, 해결이 필요한 ```Issue```일 경우 ```Pull request``` 요청을 드릴게요.

@ ```Pull request``` 를 진행하실 때는, 본 프로젝트의 ```contribute``` 브랜치에 요청해주세요.

1. 이슈 제목
데이터 연산 시간 축소

2. 이슈 발생 환경
  2.1 이슈 환경 window
  2.2 기타 환경 (특정 코드 지적 가능)

3. 이슈 내용
 3.1 자세한 내용
데이터 연산 시간이 너무 오래 걸립니다.
필요한 정보에 대한 연산 이외의 다른 구역 연산시간을 줄이는 방식 등으로의 최적화가 필요할 거 같습니다.
 3.2 스크린샷 및 결과 로그

**Comment by sangminBangbada** [comment]
풀리퀘스트 받았고,
본 프로젝트와 연동시켰습니다.
감사합니다
